Feature : add LOV Migration Script
ontoportal-lirmm/ncbo_cron pull request #24
Opened 2024-10-21 08:37 UTC by muhammedBkf

2024-10-23 06:45 UTC, syphax-bouazzouni requested changes
I updated the code to be more structured into modules: `DumpParser`, `CSVGenerator` and a object for each of the models to migrate: `Vocabulary`, `Agent` and `Distribution`.

I optimized the n3 parsing code, to not save all the graph in memory, but just building a Hash, while streaming each line/statement on the graph.

Before optimization:
```
➜  ncbo_cron git:(lov_migrator) ✗ bin/lov_migrator --all 
File downloaded successfully as lov.n3.gz.tmp
The local file remains unchanged.
Parsing the n3 file in memory
Parsing the n3 file in memory ended in 150.80259921000106 seconds
Find vocabularies start
Find vocabularies ended in 0.02299319504527375 seconds
Found 861 vocabularies:
```

After optimization:
```
➜  ncbo_cron git:(lov_migrator) ✗ bin/lov_migrator --all 
File downloaded successfully as lov.n3.gz.tmp
The local file remains unchanged.
Parsing the n3 file in memory
Parsing the n3 file in memory ended in 11.830599968961906 seconds with 861 subjects found
Find vocabularies ended in 5.6899734772741795e-06 seconds 
```

Check my commits to see the details and understand the process.

2024-10-23 06:45 UTC, syphax-bouazzouni commented on bin/lov_migrator
> +      def extract_distribution_info(graph, distribution_uri)
to update to work with the graph as an hash

2024-10-23 06:45 UTC, syphax-bouazzouni commented on bin/lov_migrator
> +      def extract_agent_info(graph, agent_uri)
to update to work with the  graph as an hash

2024-10-23 06:45 UTC, syphax-bouazzouni commented on bin/lov_migrator
> +def print_vocabulary_info(info)
to remove not needed in the final version

2024-10-23 06:45 UTC, syphax-bouazzouni commented on bin/lov_migrator
> +CSV_DISPATCH_FILENAME = 'LOV_vocabularies_dispatch.csv'
this need to be an argument of the script

2024-10-23 06:58 UTC, muhammedBkf commented
> I updated the code to be more structured into modules: `DumpParser`, `CSVGenerator` and a object for each of the models to migrate: `Vocabulary`, `Agent` and `Distribution`.
> 
> I optimized the n3 parsing code, to not save all the graph in memory, but just building a Hash, while streaming each line/statement on the graph.
> 
> Before optimization:
> 
> ```
> ➜  ncbo_cron git:(lov_migrator) ✗ bin/lov_migrator --all 
> File downloaded successfully as lov.n3.gz.tmp
> The local file remains unchanged.
> Parsing the n3 file in memory
> Parsing the n3 file in memory ended in 150.80259921000106 seconds
> Find vocabularies start
> Find vocabularies ended in 0.02299319504527375 seconds
> Found 861 vocabularies:
> ```
> 
> After optimization:
> 
> ```
> ➜  ncbo_cron git:(lov_migrator) ✗ bin/lov_migrator --all 
> File downloaded successfully as lov.n3.gz.tmp
> The local file remains unchanged.
> Parsing the n3 file in memory
> Parsing the n3 file in memory ended in 11.830599968961906 seconds with 861 subjects found
> Find vocabularies ended in 5.6899734772741795e-06 seconds 
> ```
> 
> Check my commits to see the details and understand the process.
> 
> And add always a description to your PRs.

The time gain from using a ruby hash instead of loading the hash in memory is pretty impressive. I will update the script accordingly, thanks for the review.

2024-11-08 09:49 UTC, muhammedBkf commented
It's closed, replaced by [PR#26](https://github.com/ontoportal-lirmm/ncbo_cron/pull/26)

2024-11-08 09:49 UTC, closed without merging